
const data = [
  { "replies" : [ { "author" : "Edwardo Weissnat", "authorIsCreator" : true, "profilePicture" : "https://i.postimg.cc/dV6RjdS4/Screen-Shot-2018-11-01-at-10-57-32-AM.png", "createdAt" : {$date:("2018-11-01T11:42:04.872Z")}, "body" : "Non autem accusamus. Doloremque praesentium impedit natus iure quam. Corporis tenetur hic corporis ut tempore. Quisquam voluptatem veritatis possimus architecto voluptatem quia." } ], 
    "id" : 16, "author" : "Tom Dooley", 
    "authorIsCreator" : false, 
    "profilePicture" : "https://i.postimg.cc/Z5WYwzw2/Screen-Shot-2018-11-01-at-11-02-00-AM.png", 
    "createdAt" : {$date:("2018-11-01T04:25:08.492Z")}, 
    "body" : "Maiores quia et et impedit sapiente laboriosam at excepturi. Soluta voluptate quo magnam ut qui dolores dolorum repudiandae. In doloribus distinctio aut eum provident sint officia. Reprehenderit eligendi similique dolor amet et nemo tempora cumque voluptas. Error voluptatem culpa magnam rerum. Voluptatem corporis consequatur natus quo.\n \rLibero officiis eligendi. Inventore in dolores voluptatem id consectetur. Commodi dolorem sed sit et hic hic facere numquam maxime. Aut aut ea eveniet placeat. Aspernatur ut minima repellendus nihil suscipit quod.\n \rSaepe labore laudantium perferendis debitis. Ipsam cum velit delectus. Ea ut ut fugit dolores consequatur fuga.", "__v" : 0 },
  { "replies" : [ { "author" : "Odessa Bernier", "authorIsCreator" : true, "profilePicture" : "https://i.postimg.cc/RFLvWS06/Screen-Shot-2018-11-01-at-11-03-53-AM.png", "createdAt" : {$date:("2018-10-31T23:44:40.377Z")}, "body" : "Voluptates qui qui. Placeat sint eos. Exercitationem et inventore facilis itaque qui et. Nobis dolore modi quidem. Necessitatibus sit itaque non facere architecto architecto.\n \rTempora iure voluptatum reiciendis tempore iure voluptatem. Voluptatem architecto sequi nulla sunt qui hic vel. Nesciunt sunt recusandae. Voluptatem natus quia suscipit saepe totam. Nostrum dolor voluptate non aliquid omnis quam reiciendis.\n \rQui labore quo quam qui recusandae dicta omnis illo neque. Facere voluptates natus. Quasi vero voluptatem est sunt dolorem eum. Voluptate quaerat nihil." } ], 
    "id" : 17, "author" : "Alfredo Johnston", 
    "authorIsCreator" : false, 
    "profilePicture" : "https://i.postimg.cc/mZVbRgqK/Screen-Shot-2018-11-01-at-11-04-09-AM.png", 
    "createdAt" : {$date:("2018-11-01T00:02:46.211Z")},
    "body" : "Ratione eius error. Et ex doloremque consequatur dolore quasi nulla est. Esse deserunt distinctio suscipit deleniti molestiae adipisci vitae.\n \rRerum illo sed molestiae et delectus similique dolore eos. Est quibusdam fuga libero. Quibusdam omnis ipsam voluptates quis reprehenderit quod quia. Nulla cupiditate adipisci nostrum expedita illum inventore dolorem. Quod id eum voluptatem at debitis voluptates est.\n \rMollitia et perspiciatis a. Doloremque accusamus eius vero cum tenetur sit explicabo sit voluptas. Laborum optio iure. Accusamus voluptas voluptatem eos maxime cum odit deserunt ea. Magni maxime minus enim quia est vitae sequi debitis. Magni sunt voluptatum occaecati ea.", "__v" : 0 },
  { "replies" : [ { "author" : "Leann Mraz", "authorIsCreator" : false, "profilePicture" : "https://i.postimg.cc/W3B017hb/Screen-Shot-2018-11-01-at-10-57-57-AM.png", "createdAt" : {$date:("2018-11-01T05:25:13.386Z")}, "body" : "Et sunt dolorem quo quae sequi. Officiis optio ipsa. Sit dolorem quia recusandae enim commodi veritatis autem dolor qui.\n \rItaque iure eos dolorem. Ab vel rerum ut incidunt eius et. Doloremque non quibusdam praesentium eum ad voluptatem ut. Distinctio magni atque minus aut alias repellendus ipsam odio qui. Quam rerum voluptas sed ut. Occaecati ex necessitatibus et qui adipisci culpa nemo.\n \rUt necessitatibus accusamus id similique suscipit vel rerum. Autem earum eum expedita. Rerum enim et nemo. Eaque pariatur dolor in quaerat possimus. Fugit nesciunt pariatur suscipit rerum. Facilis dignissimos quia voluptatem accusamus voluptas a." } ], 
    "id" : 18, "author" : "Willard Rodriguez", 
    "authorIsCreator" : true, 
    "profilePicture" : "https://i.postimg.cc/Z5WYwzw2/Screen-Shot-2018-11-01-at-11-02-00-AM.png", 
    "createdAt" : {$date:("2018-11-01T13:19:53.691Z")}, 
    "body" : "Dicta recusandae asperiores aspernatur necessitatibus quo ipsa et. Laudantium quis earum quam iusto. Sit necessitatibus voluptatum officia.\n \rMinus facere molestiae adipisci officiis ducimus architecto occaecati sint corrupti. Ut et unde itaque aliquid cupiditate omnis similique. Consequuntur iure velit ab dolore perferendis dolores. Soluta provident quia cumque sed. Veniam rerum impedit autem cum aut in et.\n \rAliquam laboriosam eos placeat quidem aut officia. Nisi sed eligendi quis tempora iusto et aspernatur voluptatem. Consequatur repellat quia ab sunt eaque qui non natus nihil. Ut quod praesentium impedit consequuntur labore est enim. Ad eos ipsam quis est temporibus et maxime odio consequatur.", "__v" : 0 },
  { "replies" : [ { "author" : "Mrs. Gonzalo Ullrich", "authorIsCreator" : true, "profilePicture" : "https://i.postimg.cc/JzSrgYgn/Screen-Shot-2018-11-01-at-11-02-52-AM.png", "createdAt" : {$date:("2018-11-01T04:59:23.175Z")}, "body" : "Sequi voluptatem laboriosam commodi tempora excepturi exercitationem sit aspernatur. Nihil vel corrupti. Ea rerum ut est quam saepe sit non maiores voluptate. Suscipit sit quasi ullam quia suscipit.\n \rQuo fugit eum hic quidem nam earum temporibus eaque eum. Temporibus omnis ex id. Molestiae non inventore dolor voluptatum qui iusto. Sit vero qui culpa. Repudiandae eligendi quam in dignissimos voluptatem.\n \rEst eius tempora libero perferendis quam dolor consequatur. Eaque beatae sed mollitia porro praesentium eos modi sint ut. Quae perferendis libero modi veniam aliquam veniam. Natus fugiat incidunt alias ut asperiores quaerat modi ut autem." } ], 
    "id" : 19, "author" : "Alexandra Rowe", 
    "authorIsCreator" : false, 
    "profilePicture" : "https://i.postimg.cc/8CnhqGGv/Screen-Shot-2018-11-01-at-10-57-47-AM.png", 
    "createdAt" : {$date:("2018-11-01T17:03:26.770Z")}, 
    "body" : "Placeat molestiae omnis enim aut qui optio. Ullam natus ratione eveniet qui est vel voluptas aspernatur dolorem. Accusantium culpa voluptatem non et. Autem cumque quae. Unde unde ea quam aliquid ut.", "__v" : 0 }
];

export default data;